language: node_js
dist: xenial

addons:
  apt:
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git
    - jq
    - libevent-dev
    - libncurses-dev
    - wget
    - unzip
    - tmux
    - pcre2-utils

install:
  - npm install -g markdown-table-cli

script:
  - bash ./steamcmd_appid_servers.sh

after_success:
  - .travis/push.sh

env:
  global:
    secure: "pwen4L44yq7t8UsbC489zdhMJLrKpvFKMaC1YBe4/hszFuJ7T52WoF2faFu7rRKm+NMVNDqdhIJq6HgI6I1VC2hchohI99fkmRVU879p7vI3wnleOPcXnZzgAZembCxmSUWjTgTSWrkLkVIPcJkpWKq7qml14nFmNPH6F7aMThxMabRtG66goez7npY/gJvR3/t6OCgeeFQthrnneRFO32quE9CN/NEmxhomRJ+97Fg6x94YrKhu6teIL6P5tolarGl50+g7AC/4dwLwmWINRL1asETVGrHueKrOo8VCHtu1aCYtJlIiJotJ+34Newjj8m29bM++ai1qYS+7zg0Ek+ELqFmdAIyBVQoXhAMd1cT7qXru/ocrWo2HZt2RFLN5nryf2DzAvoNPbkL0SQl3yJS+PI1pjTDqNLe9LHy34CIeQWYHJxFe7x6IErAbNYeN+TQaUnAOOy2PAboPhRtu94q2wGHgemK2/CAGnB2jfi9Lr6uWDPvpCJ9j0iZLtHyjusud359jjOxOrQlFvAyE+XXRaP6inEmd+VCPpW+L8lzlXkxjnxG/q/8lxf2OtRGbhX92ANcO07zAhxilbj39U7AS1qsY8Rvdu8G3CExjH59Ro38ankmlEHKdScxGEn8P4ISMlDh5SvG2NevShQog0JfwGV/DbhbIDKy3hpMGX/E="
